# Generated by Django 5.0.1 on 2024-01-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniuser',
            name='user_type',
            field=models.CharField(choices=[('Stock User', 'Stock User'), ('Production User', 'Production User'), ('Sales User', 'Sales User'), ('Purchase User', 'Purchase User')], default=('Stock User', 'Stock User'), help_text='<h2 style="color: #008CBA;">Set user type if user is customer or sales.</h2>', max_length=200),
        ),
    ]
