# Generated by Django 5.0.1 on 2024-01-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, unique=True)),
                ('product_group', models.CharField(default='Finished Group', max_length=300)),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('avg_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
