# Generated by Django 5.0.1 on 2024-02-01 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, unique=True)),
                ('product_group', models.CharField(default='Finished Group', max_length=300)),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_challan_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sales_order', models.CharField(max_length=50)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.deliverychallan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE')], default=('OPEN', 'OPEN'), max_length=100, null=True)),
                ('production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cost_type', models.CharField(blank=True, max_length=250, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.productissue')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchas_order_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE')], default=('OPEN', 'OPEN'), max_length=100, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.productissue')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('raw_materials', models.CharField(max_length=50)),
                ('product_issue', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchas_receipt_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.productissue')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceiptProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('raw_materials', models.CharField(max_length=50)),
                ('purchase_order', models.CharField(max_length=50)),
                ('product_issue', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('purchase_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.purchasereceipt')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_materials_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE')], default=('OPEN', 'OPEN'), max_length=100, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.productissue')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='raw_materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.rawmaterials'),
        ),
        migrations.CreateModel(
            name='RawMaterialsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_issue', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('raw_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.rawmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE')], default=('OPEN', 'OPEN'), max_length=100, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_entry_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('product_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.productissue')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_issue', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.stockentry')),
            ],
        ),
    ]
