# Generated by Django 5.0.1 on 2024-02-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE')], default=('OPEN', 'OPEN'), max_length=100),
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE')], default=('OPEN', 'OPEN'), max_length=100),
        ),
    ]
