# Generated by Django 5.0.1 on 2024-02-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0002_alter_purchaseorder_status_alter_rawmaterials_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE')], default=('OPEN', 'OPEN'), max_length=100),
        ),
    ]
