# Generated by Django 5.0.1 on 2024-02-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0003_alter_salesorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereceipt',
            old_name='purchas_receipt_no',
            new_name='purchase_receipt_no',
        ),
    ]
