# Generated by Django 5.0.1 on 2024-01-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0004_alter_product_avg_rate_alter_product_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtype',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productissue',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
