# Generated by Django 5.0.1 on 2024-01-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0005_alter_costtype_total_alter_productissue_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productissue',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
