# Generated by Django 5.0.1 on 2024-02-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0005_product_is_finished_good'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchas_order_no',
            new_name='purchase_order_no',
        ),
    ]
