# Generated by Django 5.0.1 on 2024-01-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0006_alter_productissue_production_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productissue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
