# Generated by Django 5.0.1 on 2024-02-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0006_rename_purchas_order_no_purchaseorder_purchase_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productissue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE')], default=('OPEN', 'OPEN'), max_length=100),
        ),
    ]
