# Generated by Django 5.0.1 on 2024-01-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0007_alter_productissue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productissue',
            name='total_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
