# Generated by Django 5.0.1 on 2024-01-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0008_alter_productissue_total_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallan',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaserecipt',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rawmaterials',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='product',
        ),
        migrations.CreateModel(
            name='DeliveryChallanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sales_order', models.CharField(max_length=50)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.deliverychallan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('raw_materials', models.CharField(max_length=50)),
                ('product_issue', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceiptProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('raw_materials', models.CharField(max_length=50)),
                ('purchase_order', models.CharField(max_length=50)),
                ('product_issue', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('purchase_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.purchaserecipt')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_issue', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('raw_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.rawmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('product_issue', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.product')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueChainApp.stockentry')),
            ],
        ),
    ]
