# Generated by Django 5.0.1 on 2024-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0008_alter_product_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_market_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
