# Generated by Django 5.0.1 on 2024-01-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0009_remove_deliverychallan_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='delivery_challan_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productissue',
            name='issue_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchas_order_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaserecipt',
            name='purchas_receipt_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='raw_materials_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_order_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='stock_entry_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
