# Generated by Django 5.0.1 on 2024-01-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueChainApp', '0010_deliverychallan_delivery_challan_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherscost',
            name='cost_type',
        ),
        migrations.AlterField(
            model_name='productioncost',
            name='cost_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='otherscost',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='otherscost',
            name='product_issue',
        ),
        migrations.DeleteModel(
            name='CostType',
        ),
        migrations.DeleteModel(
            name='OthersCost',
        ),
    ]
